[ui]
is_visible = 1
show_in_nav = true
label = Pony Poll

[launcher]
author = tbaublys@splunk.com
description = Interactive polling and quiz app for Splunk
version = 1.0.9

[package]
check_for_updates = false
id = ponypollapp

[id]
name = ponypollapp
version = 1.0.9

[install]
allows_disable = true
python.version = python3

[triggers]
reload.storage.collections = simple
