[script:ponypoll_api]
match                 = /ponypoll/v1
script                = ponypoll_rest.py
scripttype            = persist
handler               = ponypoll_rest.PonyPollRest
requireAuthentication = true
output_modes          = json
passPayload           = true
passHttpHeaders       = true
passHttpCookies       = true
