[expose:ponypoll_api]
pattern = ponypoll/v1/*
methods = GET,POST

[expose:ponypoll_kv_questions]
pattern = storage/collections/data/ponypoll_questions*
methods = GET,POST,DELETE

[expose:ponypoll_kv_config]
pattern = storage/collections/data/ponypoll_config*
methods = GET,POST,DELETE

[expose:ponypoll_kv_quizzes]
pattern = storage/collections/data/ponypoll_quizzes*
methods = GET,POST,DELETE

[expose:ponypoll_receivers]
pattern = receivers/simple*
methods = POST

[expose:ponypoll_search]
pattern = search/jobs*
methods = GET,POST

[expose:ponypoll_kv_session]
pattern = storage/collections/data/ponypoll_session*
methods = GET,POST,DELETE

[expose:ponypoll_kv_presence]
pattern = storage/collections/data/ponypoll_presence*
methods = GET,POST,DELETE

[expose:ponypoll_indexes]
pattern = data/indexes*
methods = GET
